name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          components: clippy, rustfmt

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Check formatting
        run: cargo fmt  -- --check

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -Dclippy::all

      - name: Build
        run: cargo build --all --release

      - name: Name Release
        if: startsWith(github.ref, 'refs/tags/')
        id: name_release
        run: echo ::set-output name=RELEASE::xorf-generator-${GITHUB_REF/refs\/tags\//}-linux.x64

      - name: Prepare Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NAME: ${{ steps.name_release.outputs.RELEASE }}
        run: |
          tar -zcvf $NAME.tar.gz -C target/release xorf-generator
          sha256sum -b --tag $NAME.tar.gz > $NAME.checksum

      - name: Push Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.name_release.outputs.RELEASE }}.tar.gz
            ${{ steps.name_release.outputs.RELEASE }}.checksum
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Build
        run: cargo build --all --release

      - name: Name Release
        if: startsWith(github.ref, 'refs/tags/')
        id: name_release
        run: echo ::set-output name=RELEASE::xorf-generator-${GITHUB_REF/refs\/tags\//}-macos.x64

      - name: Prepare Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NAME: ${{ steps.name_release.outputs.RELEASE }}
        run: |
          gtar -zcvf $NAME.tar.gz -C target/release xorf-generator
          shasum -a 256 -b --tag $NAME.tar.gz > $NAME.checksum

      - name: Push Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.name_release.outputs.RELEASE }}.tar.gz
            ${{ steps.name_release.outputs.RELEASE }}.checksum
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm
          key: llvm-11.0

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV

      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          default: true
          override: true

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Build
        run: cargo build --all --release

      - name: Name Release
        if: startsWith(github.ref, 'refs/tags/')
        id: name_release
        run: echo ::set-output name=RELEASE::xorf-generator-${GITHUB_REF/refs\/tags\//}-win.x64
        shell: bash

      - name: Prepare Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NAME: ${{ steps.name_release.outputs.RELEASE }}
        run: |
          cd /D target/release 
          7z a "$env:NAME.zip" xorf-generator.exe
          certUtil -hashfile "$env:NAME.zip" SHA256 > "$env:NAME.checksum"

      - name: Push Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.name_release.outputs.RELEASE }}.zip
            ${{ steps.name_release.outputs.RELEASE }}.checksum
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
